const CREATE_CONVERSATION_REQUEST = "CREATE_CONVERSATION_REQUEST";
const SEARCH_USER_BY_USERNAME = "SEARCH_USER_BY_USERNAME";
const GET_ALL_CONVERSATIONS_REQUEST = "GET_ALL_CONVERSATIONS_REQUEST";
const GET_CONVERSATION_BY_ID = "GET_CONVERSATION_BY_ID";
const GET_PROFILE_BY_ID = "GET_PROFILE_BY_ID";
const GET_CONVERSATION_BY_ID_REQUEST = "GET_CONVERSATION_BY_ID_REQUEST";
const SEND_MESSAGE = "SEND_MESSAGE";
const RECEIVE_MESSAGE = "RECEIVE_MESSAGE";
const NEW_CONVERSATION = "NEW_CONVERSATION";
const GET_AUTHENTICATED_USER = "GET_AUTHENTICATED_USER";
const UPDATE_BIO = "UPDATE_BIO";
const UPDATE_USERNAME = "UPDATE_USERNAME";

export {
  CREATE_CONVERSATION_REQUEST,
  SEARCH_USER_BY_USERNAME,
  GET_ALL_CONVERSATIONS_REQUEST,
  GET_CONVERSATION_BY_ID,
  GET_PROFILE_BY_ID,
  GET_CONVERSATION_BY_ID_REQUEST,
  SEND_MESSAGE,
  RECEIVE_MESSAGE,
  NEW_CONVERSATION,
  GET_AUTHENTICATED_USER,
  UPDATE_BIO,
  UPDATE_USERNAME,
};
